In [1]:
import numpy as np

In [2]:
# seed(seed=60), you will get the same sequence of values
np.random.seed(seed=60)
random_matrix = np.random.rand(5,5)
print(random_matrix)

print(f"1st row and 1st column = {random_matrix[0]}")

print(f"1st column in all rows = {random_matrix[:,0]}")

random_matrix_mean = random_matrix.mean()
print(f"Mean of the matrix = {random_matrix_mean}")

first_row_random_matrix_mean = random_matrix[0].mean()
print(f"Mean of the 1st row = {first_row_random_matrix_mean}")

[[0.30087333 0.18694582 0.32318268 0.66574957 0.5669708 ]
 [0.39825396 0.37941492 0.01058154 0.1703656  0.12339337]
 [0.69240128 0.87444156 0.3373969  0.99245923 0.13154007]
 [0.50032984 0.28662051 0.22058485 0.50208555 0.63606254]
 [0.63567694 0.08043309 0.58143375 0.83919086 0.29301825]]
1st row and 1st column = [0.30087333 0.18694582 0.32318268 0.66574957 0.5669708 ]
1st column in all rows = [0.30087333 0.39825396 0.69240128 0.50032984 0.63567694]
Mean of the matrix = 0.42917627159618377
Mean of the 1st row = 0.4087444389228477


In [3]:
%%time
# how long it takes to generate a matrix with 10 million entries and compute the mean
np.random.seed(seed=60)
big_matrix = np.random.rand(100000, 100)
big_matrix.mean()

CPU times: user 87.8 ms, sys: 40 ms, total: 128 ms
Wall time: 127 ms


0.5001528493018508

In [6]:
# create an ndarray containing all values between 1 to 100
one_to_hundred = np.arange(1, 101)

# Reshape the array to 20 rows and 5 columns
oth_reshaped = one_to_hundred.reshape(20, 5)

oth_reshaped_reduced = oth_reshaped - 50
print(f"# reshaped and subtracted by 50 = {oth_reshaped_reduced}")

oth_reshaped_multiplied = oth_reshaped * 10
print(f"# reshaped and multiplied by 10 = {oth_reshaped_multiplied}")

# reshaped and subtracted by 50 = [[-49 -48 -47 -46 -45]
 [-44 -43 -42 -41 -40]
 [-39 -38 -37 -36 -35]
 [-34 -33 -32 -31 -30]
 [-29 -28 -27 -26 -25]
 [-24 -23 -22 -21 -20]
 [-19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10]
 [ -9  -8  -7  -6  -5]
 [ -4  -3  -2  -1   0]
 [  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]]
# reshaped and multiplied by 10 = [[  10   20   30   40   50]
 [  60   70   80   90  100]
 [ 110  120  130  140  150]
 [ 160  170  180  190  200]
 [ 210  220  230  240  250]
 [ 260  270  280  290  300]
 [ 310  320  330  340  350]
 [ 360  370  380  390  400]
 [ 410  420  430  440  450]
 [ 460  470  480  490  500]
 [ 510  520  530  540  550]
 [ 560  570  580  590  600]
 [ 610  620  630  640  650]
 [ 660  670  680  690  700]
 [ 710  720  730  740  750]
 [ 760  770  780  790  800]
 [ 810  820  830  840  